RestSys/Controllers/HomeController.cs
using RestSys.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity.Core.Objects;
using System.Data.Entity;
namespace RestSys.Controllers
{
    public class HomeController : Controller
    {
        RSDbContext db = new RSDbContext();

        [Authorize]
        public ActionResult Index()
        {
            ViewBag.Username = (User.Identity as RSUser).Username;
            ViewBag.Name = (User.Identity as RSUser).Name;

            ViewBag.TodayOrdersTotal = db.Orders
                .Where(o => DbFunctions.TruncateTime(o.CreatedOn) == DbFunctions.TruncateTime(DateTime.Now))
                .Include("Items")
                .ToList()
                .Where(o => o.Items != null)
                .Sum(o => o.Items.Sum(oi => oi.Price));

            ViewBag.MostPopularProducts = db.Products
                .Include("DependentOrderItems")
                .OrderBy(p => p.DependentOrderItems.Count)
                .Take(5);

            ViewBag.StocksLowOnStock = db.Stocks.
                Where(s => s.Quantity < s.CriticalQuantity && s.CriticalQuantity > 0)
                .OrderBy(s => s.Quantity / s.CriticalQuantity)
                .Take(5);

            ViewBag.TodayMostUsedStock = db.Orders
                .Where(o => DbFunctions.TruncateTime(o.CreatedOn) == DbFunctions.TruncateTime(DateTime.Now))
                .SelectMany(o => o.Items)
                .SelectMany(oi => oi.Product.Stocks)
                .GroupBy(si => si.Product.Id)
                .OrderBy(g => g.Count())
                .Select(g => new
                {
                    Title = g.FirstOrDefault().Stock.Title,
                    Quantity = g.Sum(si => si.Amount),
                    Unit = g.FirstOrDefault().Stock.Unit
                })
                .ToList()
                .Select(g => new RSStock()
                {
                    Title = g.Title,
                    Unit = g.Unit,
                    Quantity = g.Quantity
                });

            return View(db);
        }

        public ActionResult ServerIdentification()
        {
            return Content("A2903CDE-B4EF-455F-BA8B-30465ADD2633");
        }
    }
}

RestSys/Controllers/StylesController.cs
using RestSys.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace RestSys.Controllers
{
    [Authorize]
    public class StylesController : Controller
    {
        RSDbContext db = new RSDbContext();

        public ActionResult Receipt(int id)
        {
            RSReceipt receipt = db.Receipts.Include("Order").Include("PaidItems.Product").SingleOrDefault(r => r.Id == id);
            if (receipt != null)
                return View(receipt);
            else return HttpNotFound();
        }

        public ActionResult ReceiptStyle()
        {
            return Content(GetStyleCode(RSStyleType.ReceiptStyle), "text/css");
        }

        public ActionResult Menu()
        {
            return View(db.Products.Include("Stocks.Stock").Where(p => p.ShowOnMenu));
        }

        public ActionResult MenuStyle()
        {
            return Content(GetStyleCode(RSStyleType.MenuStyle), "text/css");
        }

        private string GetStyleCode(RSStyleType type)
        {
            RSStyle style = db.Styles.Where(s => s.Type == (int)type).FirstOrDefault(s => s.Selected);
            if (style == null)
                return "";

            if (System.IO.File.Exists(Server.MapPath(style.Path)))
            {
                using (StreamReader sr = new StreamReader(Server.MapPath(style.Path)))
                {
                    return sr.ReadToEnd();
                }
            }
            else return style.Code;
        }
    }
}

RestSys/Views/Home/Index.cshtml
@model RSDbContext
@using RestSys.Resources
@using RestSys.Models;
<h2>@Resources.Dashboard</h2>
<div id="dashboard">
    <div class="dashboard-item">
        <p class="dashboard-desc">Informace o uživateli</p>
        <p class="dashboard-data">
            <strong>Přihlašovací jméno: </strong>  @ViewBag.Username<br />
            <strong>Jméno: </strong> @ViewBag.Name<br />
            @Html.ActionLink(Resources.Logout, "Logout", "Account")
        </p>
    </div>

	<div class="dashboard-item">
		<p class="dashboard-desc">Vygenerovat Menu</p>
		<p>
			@Html.ActionLink("Generovat", "Menu", "Styles")
		</p>
	</div>

    <div class="dashboard-item">
        <p class="dashboard-desc">Celková hodnota objednávek za dnešní den</p>
        <p class="dashboard-data">@ViewBag.TodayOrdersTotal  Kč</p>
    </div>

    <div class="dashboard-item">
        <p class="dashboard-desc">Zboží s nízkým množství na skladě</p>
        <p class="dashboard-data">
            <ul>
                @foreach (var stock in ViewBag.StocksLowOnStock)
                {
                    <li>@stock.Title - @stock.Quantity @stock.Unit</li>
                }
            </ul>
        </p>
    </div>

    <div class="dashboard-item">
        <p class="dashboard-desc">Využité zboží za dnešní den</p>
        <p class="dashboard-data">
			<ul>
				@foreach (dynamic stock in ViewBag.TodayMostUsedStock)
				{
					<li>@stock.Title - @stock.Quantity @stock.Unit</li>
				}
			</ul>

        </p>
    </div>

    <div class="dashboard-item">
        <p class="dashboard-desc">Nejpopulárnější produkty</p>
        <p class="dashboard-data">
            <ol>
                @foreach (var product in ViewBag.MostPopularProducts)
                {
                    <li>@product.Title</li>
                }
            </ol>
        </p>
    </div>
</div>